<html>
<head>
<link rel = "stylesheet" href = "container.css">
<title> E-PDS </title>
<style>

img
{
float:left;
margin:0 0 10px 10px;
}

</style>
</head>
<body style="background-image:url(bg.jpg);background-size:cover">
	<table align="center">
<tr><td><img src = "logo.png" width = "140" height = "140">
<font color = "blue" size = "+2" face="algerian">
<td><h1 style="font-family:ravie;color:red">E-Public Distribution System</h1>
</font>
</tr>
</table>
<font color = "blue">
<marquee><h2 style="background-color:yellow"><i>E-Public Distribution System website is availble in 24*7. Using this website ration card holder can order his/her grocery items</i></h2></marquee></font>

<div id = "main_layout">
<div id = "container">
<ul>


<li><a href = "index.php">About</a></li>
<li><a href = "signup.php">Consumer SignUp</a></li>
<li><a href = "shopowner.php">Fair Shop Owner SignUp</a></li>
<li><a href = "login.php">Login</a></li>
<li><a href = "FpmsAdminLogout.php">FAQ</a></li>

</ul>
</div>
</div>
<br><br><br>
<script>
var images = [];
var i = 0;
images[0] = "image1.jpg";
images[1] = "image2.jpg";
images[2] = "image3.jpg";
images[3] = "image4.jpg";
images[4] = "image5.jpg";
function Myimage()
{
document.getElementById('slide').src = images[i];
if(i < images.length - 1)
{
i++;
}
else
{
i=0;
}
setTimeout("Myimage()",2000);
}
</script>
<p align = "left"> <img src = "" alt = "" width = "800" height = "450" id = "slide" align = "left">
</p>
<script>
Myimage();
</script>
<h2 style="font-family:ravie;color:white">E-PDS:</h2>
<h4 style="font-family: Arial Black;color:yellow">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
During this lockdown, consumers should not go outside to buy the grocery items at the respective ration shops.Our main motive is to avoid the crowd people in order to stop the spreading Covid-19 amoung people when buying the grocery items at the Fair price shops. so that we created the web based application called E- Public Distribution system. In this portal, consumers can easily order the grocery items like rice, sugar, wheat, Balm oil ,Kerosene etc., Before placing the order, ensure that consumer should get the Token Number which is generated by this Portal itself. After validation of login, consumer get the token numberm through this token number only consumers can place the order at the respective Fair price shops.A Fair price shop owner assign the delivery job to the volunteers in order to deliver the ration grocery items to the consumers, which all of this information is available via their Login.
</h4>
<br>
<br>
<h3 align="center" style="color:white "><i>2020 @E-Public Distribution System. All Rights Reserved.</i></h3>
</body>
</html>
